const CartActionTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_CART_ITEM: "ADD_CART_ITEM",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    CART_ITEM_ADD_QUANTITY: "CART_ITEM_ADD_QUANTITY",
    CART_ITEM_REMOVE_QUANTITY: "CART_ITEM_REMOVE_QUANTITY",
    SELECTED_ATTRIBUTES_LIST: "SELECTED_ATTRIBUTES_LIST",
    SELECT_ATTRIBUTE: 'SELECT_ATTRIBUTE'
  };
  
  export default CartActionTypes;
  